/*
Garage Administration API v0+garage-v0.8.0

Administrate your Garage cluster programatically, including status, layout, keys, buckets, and maintainance tasks.  *Disclaimer: The API is not stable yet, hence its v0 tag. The API can change at any time, and changes can include breaking backward compatibility. Read the changelog and upgrade your scripts before upgrading. Additionnaly, this specification is very early stage and can contain bugs, especially on error return codes/types that are not tested yet. Do not expect a well finished and polished product!* 

API version: v0.8.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package garage

import (
	"encoding/json"
)

// ListBuckets200ResponseInner struct for ListBuckets200ResponseInner
type ListBuckets200ResponseInner struct {
	Id string `json:"id"`
	GlobalAliases []string `json:"globalAliases,omitempty"`
	LocalAliases []ListBuckets200ResponseInnerLocalAliasesInner `json:"localAliases,omitempty"`
}

// NewListBuckets200ResponseInner instantiates a new ListBuckets200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBuckets200ResponseInner(id string) *ListBuckets200ResponseInner {
	this := ListBuckets200ResponseInner{}
	this.Id = id
	return &this
}

// NewListBuckets200ResponseInnerWithDefaults instantiates a new ListBuckets200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBuckets200ResponseInnerWithDefaults() *ListBuckets200ResponseInner {
	this := ListBuckets200ResponseInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListBuckets200ResponseInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListBuckets200ResponseInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListBuckets200ResponseInner) SetId(v string) {
	o.Id = v
}

// GetGlobalAliases returns the GlobalAliases field value if set, zero value otherwise.
func (o *ListBuckets200ResponseInner) GetGlobalAliases() []string {
	if o == nil || o.GlobalAliases == nil {
		var ret []string
		return ret
	}
	return o.GlobalAliases
}

// GetGlobalAliasesOk returns a tuple with the GlobalAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBuckets200ResponseInner) GetGlobalAliasesOk() ([]string, bool) {
	if o == nil || o.GlobalAliases == nil {
		return nil, false
	}
	return o.GlobalAliases, true
}

// HasGlobalAliases returns a boolean if a field has been set.
func (o *ListBuckets200ResponseInner) HasGlobalAliases() bool {
	if o != nil && o.GlobalAliases != nil {
		return true
	}

	return false
}

// SetGlobalAliases gets a reference to the given []string and assigns it to the GlobalAliases field.
func (o *ListBuckets200ResponseInner) SetGlobalAliases(v []string) {
	o.GlobalAliases = v
}

// GetLocalAliases returns the LocalAliases field value if set, zero value otherwise.
func (o *ListBuckets200ResponseInner) GetLocalAliases() []ListBuckets200ResponseInnerLocalAliasesInner {
	if o == nil || o.LocalAliases == nil {
		var ret []ListBuckets200ResponseInnerLocalAliasesInner
		return ret
	}
	return o.LocalAliases
}

// GetLocalAliasesOk returns a tuple with the LocalAliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBuckets200ResponseInner) GetLocalAliasesOk() ([]ListBuckets200ResponseInnerLocalAliasesInner, bool) {
	if o == nil || o.LocalAliases == nil {
		return nil, false
	}
	return o.LocalAliases, true
}

// HasLocalAliases returns a boolean if a field has been set.
func (o *ListBuckets200ResponseInner) HasLocalAliases() bool {
	if o != nil && o.LocalAliases != nil {
		return true
	}

	return false
}

// SetLocalAliases gets a reference to the given []ListBuckets200ResponseInnerLocalAliasesInner and assigns it to the LocalAliases field.
func (o *ListBuckets200ResponseInner) SetLocalAliases(v []ListBuckets200ResponseInnerLocalAliasesInner) {
	o.LocalAliases = v
}

func (o ListBuckets200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.GlobalAliases != nil {
		toSerialize["globalAliases"] = o.GlobalAliases
	}
	if o.LocalAliases != nil {
		toSerialize["localAliases"] = o.LocalAliases
	}
	return json.Marshal(toSerialize)
}

type NullableListBuckets200ResponseInner struct {
	value *ListBuckets200ResponseInner
	isSet bool
}

func (v NullableListBuckets200ResponseInner) Get() *ListBuckets200ResponseInner {
	return v.value
}

func (v *NullableListBuckets200ResponseInner) Set(val *ListBuckets200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListBuckets200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListBuckets200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBuckets200ResponseInner(val *ListBuckets200ResponseInner) *NullableListBuckets200ResponseInner {
	return &NullableListBuckets200ResponseInner{value: val, isSet: true}
}

func (v NullableListBuckets200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBuckets200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


